//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLYJ.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XLYJEntities : DbContext
    {
        public XLYJEntities()
            : base("name=XLYJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<X_Student> X_Student { get; set; }
        public virtual DbSet<X_Config> X_Config { get; set; }
        public virtual DbSet<X_ConfigType> X_ConfigType { get; set; }
        public virtual DbSet<X_StudentInfo> X_StudentInfo { get; set; }
        public virtual DbSet<X_StudentInfoType> X_StudentInfoType { get; set; }
    }
}
