//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLYJ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_Config
    {
        public int ID { get; set; }
        public string ConType { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyPerson { get; set; }
    }
}
